version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO_NAME: vercel-ai-chatbot
    APP_RUNNER_SERVICE_ARN: "<set via CodeBuild env var or override>"
    GITHUB_OWNER: "javadovjavad"
    GITHUB_REPO: "vercel-ai-chatbot"
    DEPLOY_TAG_NAME: "deployed"

phases:
  install:
    commands:
      - echo "Install phase started"
      - npm install -g aws-cli || echo "aws-cli already installed"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image with Supabase env..."
      - docker build --build-arg NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$NEXT_PUBLIC_SUPABASE_ANON_KEY" -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      

      - echo "Loading GitHub token from Secrets Manager..."
      - GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id "$GITHUB_PAT_SECRET_ARN" --query SecretString --output text)

      - echo "Tagging commit on GitHub..."
      - COMMIT_SHA="$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Tagging $COMMIT_SHA as $DEPLOY_TAG_NAME"

      - |
        API_URL="https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/git/refs/tags/$DEPLOY_TAG_NAME"
        AUTH_HEADER="Authorization: token $GITHUB_TOKEN"

        # Check if tag exists
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "$AUTH_HEADER" "$API_URL")

        if [ "$STATUS" -eq 200 ]; then
          echo "Tag exists, updating..."
          curl -s -X PATCH -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            -d "{\"sha\": \"$COMMIT_SHA\", \"force\": true}" \
            "$API_URL"
        else
          echo "Tag does not exist, creating..."
          curl -s -X POST -H "$AUTH_HEADER" \
            -H "Content-Type: application/json" \
            -d "{\"ref\": \"refs/tags/$DEPLOY_TAG_NAME\", \"sha\": \"$COMMIT_SHA\"}" \
            "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/git/refs"
        fi

artifacts:
  files:
    - '**/*'
  discard-paths: yes