FROM public.ecr.aws/docker/library/node:20-alpine
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
WORKDIR /app
RUN corepack enable
COPY package*.json ./
RUN npm install --force
COPY . .
ENV NODE_ENV=production
RUN npm run build
ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]